import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Lang = "fr" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<string, Record<Lang, string>> = {
  // Navbar
  "nav.home": { fr: "Accueil", ar: "الرئيسية" },
  "nav.find": { fr: "Trouver un psychologue", ar: "ابحث عن أخصائي نفسي" },
  "nav.space": { fr: "Mon espace", ar: "مساحتي" },
  "nav.login": { fr: "Se connecter", ar: "تسجيل الدخول" },
  "nav.signup": { fr: "S'inscrire", ar: "إنشاء حساب" },
  "nav.logout": { fr: "Déconnexion", ar: "تسجيل الخروج" },
  "nav.langSwitch": { fr: "العربية", ar: "Français" },

  // Hero
  "hero.title": { fr: "Votre espace de santé mentale", ar: "مساحتك للصحة النفسية" },
  "hero.subtitle": { fr: "Connectez-vous avec des psychologues professionnels, à votre rythme, en toute confidentialité.", ar: "تواصل مع أخصائيين نفسيين محترفين، بالوتيرة التي تناسبك، بسرية تامة." },
  "hero.cta": { fr: "Trouver un psychologue", ar: "ابحث عن أخصائي نفسي" },
  "hero.how": { fr: "Comment ça marche", ar: "كيف يعمل" },
  "hero.overlay.subtitle": { fr: "Espace d'écoute", ar: "فضاء الإصغاء" },

  // Stats
  "stats.psychologists": { fr: "Psychologues certifiés", ar: "أخصائيون نفسيون معتمدون" },
  "stats.sessions": { fr: "Séances réalisées", ar: "جلسات منجزة" },
  "stats.satisfaction": { fr: "Engagement qualité", ar: "التزام بالجودة" },
  "stats.support": { fr: "Support disponible", ar: "دعم متاح" },

  // How it works
  "how.title": { fr: "Comment ça marche ?", ar: "كيف يعمل؟" },
  "how.subtitle": { fr: "Trois étapes simples pour commencer votre parcours", ar: "ثلاث خطوات بسيطة لبدء مسارك" },
  "how.step1.title": { fr: "Trouvez votre psychologue", ar: "ابحث عن أخصائيك النفسي" },
  "how.step1.desc": { fr: "Parcourez les profils et choisissez selon vos besoins", ar: "تصفح الملفات واختر حسب احتياجاتك" },
  "how.step2.title": { fr: "Réservez une séance", ar: "احجز جلسة" },
  "how.step2.desc": { fr: "Sélectionnez un créneau qui vous convient", ar: "اختر موعداً يناسبك" },
  "how.step3.title": { fr: "Commencez votre thérapie", ar: "ابدأ علاجك" },
  "how.step3.desc": { fr: "Consultez en ligne en toute sécurité", ar: "استشر عبر الإنترنت بأمان تام" },

  // Why Majal
  "why.title": { fr: "Pourquoi choisir Majal ?", ar: "لماذا تختار مجال؟" },
  "why.1.title": { fr: "Confidentiel et sécurisé", ar: "سري وآمن" },
  "why.1.desc": { fr: "Vos données sont protégées", ar: "بياناتك محمية" },
  "why.2.title": { fr: "Psychologues certifiés", ar: "أخصائيون معتمدون" },
  "why.2.desc": { fr: "Tous nos professionnels sont qualifiés", ar: "جميع المهنيين لدينا مؤهلون" },
  "why.3.title": { fr: "Flexible et accessible", ar: "مرن وسهل الوصول" },
  "why.3.desc": { fr: "Consultez de chez vous, quand vous voulez", ar: "استشر من منزلك، متى شئت" },
  "why.4.title": { fr: "Soutien personnalisé", ar: "دعم مخصص" },
  "why.4.desc": { fr: "Trouvez le thérapeute qui vous correspond", ar: "ابحث عن المعالج الذي يناسبك" },

  // Testimonials
  "test.title": { fr: "Témoignages", ar: "شهادات" },
  "test.subtitle": { fr: "Ce que disent nos utilisateurs", ar: "ماذا يقول مستخدمونا" },
  "test.1.text": { fr: "Majal m'a aidé à trouver un psychologue formidable. Je me sens enfin écoutée.", ar: "ساعدني مجال في إيجاد أخصائي نفسي رائع. أشعر أخيراً بأنني مسموعة." },
  "test.2.text": { fr: "Simple, discret et efficace. Exactement ce dont j'avais besoin.", ar: "بسيط، سري وفعال. بالضبط ما كنت أحتاجه." },
  "test.3.text": { fr: "Je recommande Majal à tous ceux qui cherchent un soutien psychologique de qualité.", ar: "أنصح بمجال لكل من يبحث عن دعم نفسي ذي جودة." },

  // CTA
  "cta.title": { fr: "Prenez soin de vous aujourd'hui", ar: "اعتنِ بنفسك اليوم" },
  "cta.subtitle": { fr: "Rejoignez des milliers de personnes qui ont fait le premier pas", ar: "انضم إلى آلاف الأشخاص الذين اتخذوا الخطوة الأولى" },
  "cta.button": { fr: "Commencer maintenant", ar: "ابدأ الآن" },

  // Footer
  "footer.tagline": { fr: "Votre espace de santé mentale en ligne", ar: "مساحتك للصحة النفسية عبر الإنترنت" },
  "footer.nav": { fr: "Navigation", ar: "التنقل" },
  "footer.support": { fr: "Support", ar: "الدعم" },
  "footer.help": { fr: "Centre d'aide", ar: "مركز المساعدة" },
  "footer.contact": { fr: "Contactez-nous", ar: "اتصل بنا" },
  "footer.faq": { fr: "FAQ", ar: "الأسئلة الشائعة" },
  "footer.legal": { fr: "Légal", ar: "قانوني" },
  "footer.privacy": { fr: "Confidentialité", ar: "الخصوصية" },
  "footer.terms": { fr: "Conditions", ar: "الشروط" },
  "footer.rights": { fr: "© 2026 Majal. Tous droits réservés.", ar: "© 2026 مجال. جميع الحقوق محفوظة." },

  // Psychologues page
  "psy.title": { fr: "Trouver votre psychologue", ar: "ابحث عن أخصائيك النفسي" },
  "psy.subtitle": { fr: "Parcourez notre réseau de professionnels certifiés", ar: "تصفح شبكتنا من المهنيين المعتمدين" },
  "psy.search": { fr: "Rechercher par nom ou spécialité...", ar: "البحث بالاسم أو التخصص..." },
  "psy.filters": { fr: "Filtres", ar: "فلاتر" },
  "psy.category": { fr: "Catégorie", ar: "الفئة" },
  "psy.subcategory": { fr: "Sous-catégorie", ar: "الفئة الفرعية" },
  "psy.activeFilters": { fr: "Filtres actifs :", ar: "الفلاتر النشطة:" },
  "psy.clearAll": { fr: "Tout effacer", ar: "مسح الكل" },
  "psy.noResults": { fr: "Aucun psychologue ne correspond à vos critères.", ar: "لا يوجد أخصائي نفسي يطابق معاييرك." },
  "psy.clearFilters": { fr: "Effacer les filtres", ar: "مسح الفلاتر" },
  "psy.talkNow": { fr: "Parler maintenant", ar: "تحدث الآن" },
  "psy.requestSending": { fr: "Envoi...", ar: "إرسال..." },
  "psy.requestPending": { fr: "Demande envoyée", ar: "تم إرسال الطلب" },
  "psy.requestPendingDesc": { fr: "En attente de la réponse du psychologue... (90s)", ar: "في انتظار رد الأخصائي... (90 ثانية)" },
  "psy.requestAccepted": { fr: "Demande acceptée !", ar: "تم قبول الطلب!" },
  "psy.requestAcceptedDesc": { fr: "Redirection vers votre session...", ar: "جارٍ التحويل إلى جلستك..." },
  "psy.requestDeclined": { fr: "Demande refusée", ar: "تم رفض الطلب" },
  "psy.requestDeclinedDesc": { fr: "Le psychologue n'est pas disponible pour le moment.", ar: "الأخصائي غير متاح في الوقت الحالي." },
  "psy.requestExpired": { fr: "Demande expirée", ar: "انتهت مهلة الطلب" },
  "psy.requestExpiredDesc": { fr: "Le psychologue n'a pas répondu dans les 90 secondes.", ar: "لم يرد الأخصائي خلال 90 ثانية." },
  "psy.requestClose": { fr: "Fermer", ar: "إغلاق" },
  "psy.incomingRequests": { fr: "Demandes de session immédiate", ar: "طلبات الجلسة الفورية" },
  "psy.accept": { fr: "Accepter", ar: "قبول" },
  "psy.decline": { fr: "Refuser", ar: "رفض" },
  "psy.specialty": { fr: "Spécialité", ar: "التخصص" },
  "psy.all": { fr: "Toutes", ar: "الكل" },
  "psy.language": { fr: "Langue", ar: "اللغة" },
  "psy.price": { fr: "Prix", ar: "السعر" },
  "psy.allPrices": { fr: "Tous", ar: "الكل" },
  "psy.available": { fr: "disponible", ar: "متاح" },
  "psy.availables": { fr: "disponibles", ar: "متاحون" },
  "psy.psychologue": { fr: "psychologue", ar: "أخصائي نفسي" },
  "psy.psychologues": { fr: "psychologues", ar: "أخصائيون نفسيون" },
  "psy.book": { fr: "Réserver", ar: "احجز" },
  "psy.availableNow": { fr: "Parler maintenant", ar: "تحدث الآن" },
  "psy.videoPresentation": { fr: "Vidéo de présentation", ar: "فيديو تعريفي" },
  "psy.settings.video.title": { fr: "Vidéo de présentation", ar: "فيديو تعريفي" },
  "psy.settings.video.desc": { fr: "Ajoutez une courte vidéo pour présenter votre approche aux patients.", ar: "أضف فيديو قصير لتقديم نهجك للمرضى." },
  "psy.settings.video.upload": { fr: "Télécharger une vidéo", ar: "رفع فيديو" },
  "psy.settings.video.remove": { fr: "Supprimer la vidéo", ar: "حذف الفيديو" },
  "psy.settings.availability.title": { fr: "Parler maintenant", ar: "تحدث الآن" },
  "psy.settings.availability.desc": { fr: "Activez ce statut pour apparaître comme disponible pour une séance immédiate. Les patients pourront vous contacter directement.", ar: "فعّل هذا الحالة لتظهر كمتاح لجلسة فورية. يمكن للمرضى التواصل معك مباشرة." },
  "psy.settings.specializations.title": { fr: "Spécialisations", ar: "التخصصات" },
  "psy.settings.specializations.desc": { fr: "Sélectionnez les domaines dans lesquels vous intervenez.", ar: "حدد المجالات التي تعمل فيها." },
  "psy.experience": { fr: "ans d'expérience", ar: "سنوات خبرة" },
  "psy.session": { fr: "/ séance", ar: "/ جلسة" },
  "psy.lessThan": { fr: "Moins de", ar: "أقل من" },
  "psy.dashboard.nav.dashboard": { fr: "Tableau de bord", ar: "لوحة القيادة" },
  "psy.dashboard.nav.sessions": { fr: "Mes séances", ar: "جلساتي" },
  "psy.dashboard.nav.patients": { fr: "Mes patients", ar: "مرضاي" },
  "psy.dashboard.nav.messages": { fr: "Messages", ar: "الرسائل" },
  "psy.dashboard.nav.earnings": { fr: "Revenus", ar: "الأرباح" },
  "psy.dashboard.nav.profile": { fr: "Profil professionnel", ar: "الملف المهني" },
  "psy.dashboard.nav.settings": { fr: "Paramètres", ar: "الإعدادات" },
  "psy.dashboard.spaceTitle": { fr: "Espace Psychologue", ar: "فضاء الأخصائي النفسي" },
  "psy.dashboard.welcome": { fr: "Bienvenue", ar: "مرحباً" },
  "psy.dashboard.welcomeSub": { fr: "Voici un aperçu de votre activité aujourd'hui", ar: "إليك نظرة عامة على نشاطك اليوم" },
  "psy.dashboard.stat.totalPatients": { fr: "Patients totaux", ar: "إجمالي المرضى" },
  "psy.dashboard.stat.sessionsMonth": { fr: "Séances ce mois-ci", ar: "جلسات هذا الشهر" },
  "psy.dashboard.stat.earnings": { fr: "Revenus ce mois-ci", ar: "أرباح هذا الشهر" },
  "psy.dashboard.stat.upcoming": { fr: "Prochaines séances", ar: "الجلسات القادمة" },
  "psy.dashboard.upcomingSessions": { fr: "Séances à venir", ar: "الجلسات القادمة" },
  "psy.dashboard.noUpcoming": { fr: "Aucune séance à venir pour le moment.", ar: "لا توجد جلسات قادمة حالياً." },
  "psy.dashboard.weeklyEarnings": { fr: "Revenus hebdomadaires", ar: "الأرباح الأسبوعية" },
  "psy.dashboard.weekTotal": { fr: "Total cette semaine", ar: "إجمالي هذا الأسبوع" },
  "psy.dashboard.recentPatients": { fr: "Patients récents", ar: "المرضى الآخرون مؤخراً" },
  "psy.dashboard.noPatients": { fr: "Aucun patient enregistré pour le moment.", ar: "لا يوجد أي مريض مسجل حالياً." },
  "psy.dashboard.sessionCount": { fr: "séance(s)", ar: "جلسة (جلسات)" },
  "psy.dashboard.lastVisit": { fr: "Dernière visite", ar: "آخر زيارة" },
  "psy.dashboard.allSessions": { fr: "Toutes les séances", ar: "جميع الجلسات" },
  "psy.dashboard.noSessions": { fr: "Aucune séance enregistrée.", ar: "لم يتم تسجيل أي جلسة." },
  "psy.dashboard.confirm": { fr: "Confirmer", ar: "تأكيد" },
  "psy.dashboard.reject": { fr: "Refuser", ar: "رفض" },
  "psy.dashboard.startVideo": { fr: "Rejoindre l'appel", ar: "انضمام للمكالمة" },
  "psy.dashboard.markDone": { fr: "Marquer comme fait", ar: "تحديد كمكتملة" },
  "psy.dashboard.myPatients": { fr: "Mes patients", ar: "مرضاي" },
  "psy.dashboard.defaultPatientName": { fr: "Patient", ar: "مريض" },
  "psy.dashboard.selectPatientMsg": { fr: "Sélectionnez un patient pour voir les détails de son suivi.", ar: "اختر مريضاً لعرض تفاصيل متابعته." },
  "psy.earnings.thisMonth": { fr: "Revenus du mois", ar: "أرباح الشهر" },
  "psy.earnings.sessionsMonth": { fr: "Séances payées", ar: "الجلسات المدفوعة" },
  "psy.earnings.pending": { fr: "En attente", ar: "قيد الانتظار" },
  "psy.earnings.sessionsPending": { fr: "Séances en attente", ar: "جلسات قيد الانتظار" },
  "psy.earnings.avgPerSession": { fr: "Moyenne par séance", ar: "متوسط الجلسة" },
  "psy.earnings.dailyChart": { fr: "Historique quotidien des revenus", ar: "سجل الأرباح اليومي" },
  "psy.earnings.recentTx": { fr: "Transactions récentes", ar: "المعاملات الأخيرة" },
  "psy.earnings.noTx": { fr: "Aucune transaction enregistrée.", ar: "لم يتم تسجيل أي معاملة." },
  "psy.dashboard.profile.professionalInfo": { fr: "Informations professionnelles", ar: "المعلومات المهنية" },
  "psy.dashboard.profile.yearsExperience": { fr: "Années d'expérience", ar: "سنوات الخبرة" },
  "psy.dashboard.profile.bio": { fr: "Biographie / Présentation", ar: "السيرة الذاتية / التعريف" },
  "psy.dashboard.profile.bioPlaceholder": { fr: "Décrivez votre approche thérapeutique, spécialités, etc...", ar: "صف منهجك العلاجي، تخصصاتك، إلخ..." },
  "psy.settings.notif.newBookingsTitle": { fr: "Nouvelles réservations", ar: "الحجوزات الجديدة" },
  "psy.settings.notif.newBookingsDesc": { fr: "Recevoir une notification lors d'une nouvelle réservation", ar: "تلقي إشعار عند وجود حجز جديد" },
  "psy.settings.notif.remindersTitle": { fr: "Rappels de séance", ar: "تذكيرات الجلسات" },
  "psy.settings.notif.remindersDesc": { fr: "Recevoir des rappels avant vos séances", ar: "تلقي تذكيرات قبل الجلسات" },
  "psy.settings.notif.messagesTitle": { fr: "Nouveaux messages", ar: "الرسائل الجديدة" },
  "psy.settings.notif.messagesDesc": { fr: "Recevoir une notification pour les nouveaux messages", ar: "تلقي إشعار عند استلام رسائل جديدة" },
  "psy.settings.notif.paymentsTitle": { fr: "Paiements et factures", ar: "المدفوعات والفواتير" },
  "psy.settings.notif.paymentsDesc": { fr: "Recevoir une confirmation lors d'un paiement réussi", ar: "تلقي تأكيد عند نجاح عملية الدفع" },
  "psy.settings.security": { fr: "Sécurité", ar: "الأمان" },
  "psy.settings.changePassword": { fr: "Changer le mot de passe", ar: "تغيير كلمة المرور" },
  "psy.dashboard.pendingTitle": { fr: "Profil en cours de vérification", ar: "الملف الشخصي قيد المراجعة" },
  "psy.dashboard.pendingDesc": { fr: "Votre profil est en cours de révision par notre équipe clinique. Vous serez averti dès son approbation.", ar: "ملفك الشخصي قيد المراجعة من قبل فريقنا الطبي. سيتم إشعارك بمجرد الموافقة عليه." },
  "psy.dashboard.rejectedTitle": { fr: "Profil rejeté", ar: "تم رفض الملف الشخصي" },
  "psy.dashboard.rejectedDesc": { fr: "Votre profil a été rejeté car vos documents d'accréditation n'ont pas pu être validés. Veuillez nous contacter pour plus d'informations.", ar: "تم رفض ملفك الشخصي لعدم إمكانية التحقق من وثائق الاعتماد الخاصة بك. يرجى الاتصال بنا للمزيد من التفاصيل." },

  // Reservation
  "res.back": { fr: "Retour au profil", ar: "العودة للملف" },
  "res.title": { fr: "Réserver une séance", ar: "احجز جلسة" },
  "res.with": { fr: "avec", ar: "مع" },
  "res.selectDate": { fr: "Sélectionnez une date", ar: "اختر تاريخاً" },
  "res.selectTime": { fr: "Sélectionnez un horaire", ar: "اختر وقتاً" },
  "res.morning": { fr: "Matin", ar: "صباحاً" },
  "res.afternoon": { fr: "Après-midi", ar: "بعد الظهر" },
  "res.evening": { fr: "Soir", ar: "مساءً" },
  "res.recap": { fr: "Récapitulatif", ar: "ملخص" },
  "res.date": { fr: "Date", ar: "التاريخ" },
  "res.time": { fr: "Horaire", ar: "الوقت" },
  "res.duration": { fr: "Durée", ar: "المدة" },
  "res.minutes": { fr: "60 minutes", ar: "60 دقيقة" },
  "res.price": { fr: "Prix", ar: "السعر" },
  "res.confirm": { fr: "Confirmer la réservation", ar: "تأكيد الحجز" },
  "res.confirmed": { fr: "Réservation confirmée !", ar: "تم تأكيد الحجز!" },
  "res.confirmMsg": { fr: "Votre séance avec", ar: "جلستك مع" },
  "res.confirmMsg2": { fr: "est confirmée le", ar: "تم تأكيدها في" },
  "res.confirmMsg3": { fr: "à", ar: "الساعة" },
  "res.confirmMsg4": { fr: "Vous recevrez un email de confirmation.", ar: "ستتلقى بريداً إلكترونياً للتأكيد." },
  "res.backToPsy": { fr: "Retour aux psychologues", ar: "العودة للأخصائيين" },

  // Calendar
  "cal.months": { fr: "Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre", ar: "يناير,فبراير,مارس,أبريل,مايو,يونيو,يوليو,أغسطس,سبتمبر,أكتوبر,نوفمبر,ديسمبر" },
  "cal.days": { fr: "Dim,Lun,Mar,Mer,Jeu,Ven,Sam", ar: "أحد,إثن,ثلا,أرب,خمي,جمع,سبت" },

  // Profile page
  "prof.back": { fr: "Retour", ar: "العودة" },
  "prof.about": { fr: "À propos", ar: "حول" },
  "prof.reviews": { fr: "Avis", ar: "التقييمات" },
  "prof.book": { fr: "Réserver une séance", ar: "احجز جلسة" },
  "prof.bookNow": { fr: "Réserver maintenant", ar: "احجز الآن" },
  "prof.message": { fr: "Envoyer un message", ar: "إرسال رسالة" },
  "prof.experience": { fr: "ans d'expérience", ar: "سنوات خبرة" },
  "prof.languages": { fr: "Langues", ar: "اللغات" },
  "prof.availability": { fr: "Disponibilités", ar: "التوفر" },
  "prof.bio": { fr: "Biographie", ar: "السيرة الذاتية" },
  "prof.approach": { fr: "Approche thérapeutique", ar: "المنهج العلاجي" },
  "prof.training": { fr: "Formation", ar: "التكوين" },
  "prof.slots": { fr: "Créneaux disponibles cette semaine", ar: "المواعيد المتاحة هذا الأسبوع" },
  "prof.session": { fr: "/ séance", ar: "/ جلسة" },
  "prof.reviewWord": { fr: "avis", ar: "تقييم" },

  // Mon Espace
  "space.title": { fr: "Mon espace", ar: "مساحتي" },
  "space.welcome": { fr: "Bienvenue 👋", ar: "مرحباً 👋" },
  "space.totalSessions": { fr: "Séances totales", ar: "إجمالي الجلسات" },
  "space.totalHours": { fr: "Heures de thérapie", ar: "ساعات العلاج" },
  "space.streak": { fr: "Série actuelle", ar: "السلسلة الحالية" },
  "space.upcoming": { fr: "Séances à venir", ar: "الجلسات القادمة" },
  "space.history": { fr: "Historique", ar: "السجل" },
  "space.profile": { fr: "Mon profil", ar: "ملفي الشخصي" },
  "space.join": { fr: "Rejoindre", ar: "انضمام" },
  "space.messageBtn": { fr: "Message", ar: "رسالة" },
  "space.done": { fr: "Terminée", ar: "منتهية" },
  "space.cancelled": { fr: "Annulée", ar: "ملغاة" },
  "space.personalInfo": { fr: "Informations personnelles", ar: "المعلومات الشخصية" },
  "space.name": { fr: "Nom", ar: "الاسم" },
  "space.email": { fr: "Email", ar: "البريد الإلكتروني" },
  "space.phone": { fr: "Téléphone", ar: "الهاتف" },
  "space.language": { fr: "Langue", ar: "اللغة" },
  "space.notifications": { fr: "Notifications", ar: "الإشعارات" },
  "space.notif.empty": { fr: "Aucune notification pour le moment", ar: "لا توجد إشعارات حالياً" },
  "space.notif.markAllRead": { fr: "Tout marquer comme lu", ar: "تحديد الكل كمقروء" },
  "space.notif.clearAll": { fr: "Effacer tout", ar: "مسح الكل" },
  "space.notif.newNotification": { fr: "Nouvelle notification", ar: "إشعار جديد" },
  "space.notif.clickToView": { fr: "Cliquez pour voir", ar: "اضغط للعرض" },
  "space.notif.booking": { fr: "Séances", ar: "جلسات" },
  "space.notif.message": { fr: "Messages", ar: "رسائل" },
  "space.notif.system": { fr: "Système", ar: "نظام" },
  "space.notif.all": { fr: "Toutes", ar: "الكل" },
  "space.notif.unread": { fr: "Non lues", ar: "غير المقروءة" },
  "space.emailNotif": { fr: "Notifications par email", ar: "إشعارات البريد الإلكتروني" },
  "space.emailNotifDesc": { fr: "Recevoir des rappels par email", ar: "استلام تذكيرات عبر البريد" },
  "space.smsNotif": { fr: "Notifications SMS", ar: "إشعارات الرسائل القصيرة" },
  "space.smsNotifDesc": { fr: "Recevoir des rappels par SMS", ar: "استلام تذكيرات عبر الرسائل" },
  "space.save": { fr: "Enregistrer les modifications", ar: "حفظ التعديلات" },
  "space.saved": { fr: "✅ Modifications enregistrées !", ar: "✅ تم حفظ التعديلات!" },
  "space.weeks": { fr: "sem.", ar: "أسابيع" },
  "space.cancel": { fr: "Annuler", ar: "إلغاء" },
  "space.continuePath": { fr: "Poursuivre votre parcours", ar: "مواصلة مسارك العلاجي" },
  "space.findPsySubtitle": { fr: "Prenez rendez-vous avec un autre praticien de notre réseau.", ar: "احجز موعداً مع أخصائي آخر من شبكتنا." },
  "space.findPsyBtn": { fr: "Trouver un psychologue", ar: "البحث عن أخصائي" },
  "space.upcomingSessionsCount": { fr: "Prochaines séances", ar: "الجلسات القادمة" },
  "space.noSessionsPlanned": { fr: "Aucune séance planifiée.", ar: "لا توجد جلسات مجدولة." },
  "space.bookSession": { fr: "Réserver une séance", ar: "حجز جلسة" },
  "space.sessionLabel": { fr: "Séance individuelle", ar: "جلسة فردية" },
  "space.minutesLabel": { fr: "minutes", ar: "دقيقة" },
  "space.priceCurrency": { fr: "DA", ar: "د.ج" },
  "space.status.confirmed": { fr: "Confirmée", ar: "مؤكدة" },
  "space.status.pending": { fr: "En attente", ar: "قيد الانتظار" },
  "space.cancelSessionBtn": { fr: "Annuler la séance", ar: "إلغاء الجلسة" },
  "space.historyCount": { fr: "Historique des séances", ar: "سجل الجلسات" },
  "space.noHistory": { fr: "Aucun historique disponible.", ar: "لا يوجد سجل متاح." },
  "space.status.done": { fr: "Terminée", ar: "منتهية" },
  "space.status.cancelled": { fr: "Annulée", ar: "ملغاة" },
  "space.discussionsTitle": { fr: "Discussions", ar: "المحادثات" },
  "space.noTherapistsMessage": { fr: "Vous n'avez pas encore de conversation active. Réservez une séance pour commencer à échanger.", ar: "les conversations actives s'affichent ici. Réservez une séance." },
  "space.defaultTherapistName": { fr: "Psychologue", ar: "أخصائي نفسي" },
  "space.selectPsyMessage": { fr: "Sélectionnez un psychologue dans la liste pour démarrer la discussion.", ar: "اختر أخصائياً نفسياً من القائمة لبدء المحادثة." },
  "space.yourName": { fr: "Votre nom", ar: "اسمك" },
  "space.fullName": { fr: "Nom complet", ar: "الاسم الكامل" },
  "space.lang.french": { fr: "Français", ar: "الفرنسية" },
  "space.lang.arabic": { fr: "العربية", ar: "العربية" },
  "space.lang.english": { fr: "English", ar: "الإنجليزية" },
  "space.saving": { fr: "Enregistrement...", ar: "جاري الحفظ..." },
  "space.notifPreferences": { fr: "Préférences de notifications", ar: "تفضيلات الإشعارات" },
  "space.notif.remindersTitle": { fr: "Rappels de séances", ar: "تذكير بالجلسات" },
  "space.notif.remindersDesc": { fr: "Recevoir des rappels 24h avant vos séances.", ar: "تلقي تذكيرات قبل 24 ساعة من الجلسات." },
  "space.notif.confirmTitle": { fr: "Confirmations de réservation", ar: "تأكيد الحجز" },
  "space.notif.confirmDesc": { fr: "Recevoir un email quand le psychologue confirme votre séance.", ar: "تلقي بريد إلكتروني عند تأكيد الأخصائي لجلساتك." },
  "space.notif.smsTitle": { fr: "Rappels par SMS", ar: "تذكير عبر الرسائل القصيرة" },
  "space.notif.smsDesc": { fr: "Recevoir un SMS de rappel sur votre téléphone.", ar: "تلقي رسالة نصية تذكيرية على هاتفك." },
  "space.notif.offersTitle": { fr: "Offres et conseils", ar: "العروض والنصائح" },
  "space.notif.offersDesc": { fr: "Recevoir nos conseils bien-être et des offres promotionnelles.", ar: "تلقي نصائح الصحة النفسية والعروض الترويجية." },
  "space.notif.successSave": { fr: "Préférences de notifications enregistrées !", ar: "تم حفظ تفضيلات الإشعارات!" },
  "space.notif.save": { fr: "Enregistrer les préférences", ar: "حفظ التفضيلات" },
  "space.dashboard": { fr: "Tableau de bord", ar: "لوحة التحكم" },
  "space.nav.sessions": { fr: "Mes séances", ar: "جلساتي" },
  "space.nav.messages": { fr: "Messages", ar: "الرسائل" },
  "space.viewAll": { fr: "Voir tout", ar: "عرض الكل" },
  "complete.step1.price": { fr: "Tarif de la séance (DA)", ar: "سعر الجلسة (د.ج)" },

  // Auth - Connexion
  "auth.welcome": { fr: "Bon retour", ar: "مرحباً بعودتك" },
  "auth.loginSubtitle": { fr: "Connectez-vous à votre espace Majal", ar: "سجل الدخول إلى مساحتك في مجال" },
  "auth.google": { fr: "Continuer avec Google", ar: "المتابعة مع جوجل" },
  "auth.or": { fr: "ou", ar: "أو" },
  "auth.email": { fr: "Email", ar: "البريد الإلكتروني" },
  "auth.password": { fr: "Mot de passe", ar: "كلمة المرور" },
  "auth.forgot": { fr: "Mot de passe oublié ?", ar: "نسيت كلمة المرور؟" },
  "auth.loginBtn": { fr: "Se connecter", ar: "تسجيل الدخول" },
  "auth.loggingIn": { fr: "Connexion...", ar: "جاري الدخول..." },
  "auth.noAccount": { fr: "Pas encore de compte ?", ar: "ليس لديك حساب؟" },
  "auth.signupLink": { fr: "S'inscrire", ar: "إنشاء حساب" },

  // Auth - Inscription
  "auth.createAccount": { fr: "Créer un compte", ar: "إنشاء حساب" },
  "auth.signupSubtitle": { fr: "Rejoignez Majal et prenez soin de vous", ar: "انضم إلى مجال واعتنِ بنفسك" },
  "auth.patient": { fr: "🧑 Particulier", ar: "🧑 فرد" },
  "auth.psychologist": { fr: "🩺 Psychologue", ar: "🩺 أخصائي نفسي" },
  "auth.fullName": { fr: "Nom complet", ar: "الاسم الكامل" },
  "auth.namePlaceholder": { fr: "Votre nom", ar: "اسمك" },
  "auth.phonePlaceholder": { fr: "+213 05X XXX XXXX", ar: "+213 05X XXX XXXX" },
  "auth.orderNumber": { fr: "Numéro d'ordre professionnel", ar: "رقم الترخيص المهني" },
  "auth.orderPlaceholder": { fr: "Ex: PSY-12345", ar: "مثال: PSY-12345" },
  "auth.specialtyLabel": { fr: "Spécialité", ar: "التخصص" },
  "auth.chooseSpecialty": { fr: "Choisir une spécialité", ar: "اختر تخصصاً" },
  "auth.clinicalPsy": { fr: "Psychologie clinique", ar: "علم النفس السريري" },
  "auth.psychotherapy": { fr: "Psychothérapie", ar: "العلاج النفسي" },
  "auth.neuropsychology": { fr: "Neuropsychologie", ar: "علم النفس العصبي" },
  "auth.childPsy": { fr: "Psychologie de l'enfant", ar: "علم نفس الطفل" },
  "auth.couplePsy": { fr: "Psychologie de couple", ar: "علم نفس الأزواج" },
  "auth.psychiatry": { fr: "Psychiatrie", ar: "الطب النفسي" },
  "auth.other": { fr: "Autre", ar: "أخرى" },
  "auth.cityLabel": { fr: "Ville d'exercice", ar: "مدينة العمل" },
  "auth.cityPlaceholder": { fr: "Ex: Casablanca", ar: "مثال: الدار البيضاء" },
  "auth.minChars": { fr: "Minimum 6 caractères", ar: "6 أحرف على الأقل" },
  "auth.signupBtn": { fr: "S'inscrire", ar: "إنشاء حساب" },
  "auth.signingUp": { fr: "Inscription...", ar: "جاري الإنشاء..." },
  "auth.hasAccount": { fr: "Déjà un compte ?", ar: "لديك حساب بالفعل؟" },
  "auth.loginLink": { fr: "Se connecter", ar: "تسجيل الدخول" },
  "auth.phone": { fr: "Téléphone", ar: "الهاتف" },

  // Forgot password
  "forgot.title": { fr: "Mot de passe oublié", ar: "نسيت كلمة المرور" },
  "forgot.subtitle": { fr: "Entrez votre email pour réinitialiser votre mot de passe", ar: "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور" },
  "forgot.send": { fr: "Envoyer le lien", ar: "إرسال الرابط" },
  "forgot.sending": { fr: "Envoi...", ar: "جاري الإرسال..." },
  "forgot.backToLogin": { fr: "Retour à la connexion", ar: "العودة لتسجيل الدخول" },
  "forgot.sentTitle": { fr: "Email envoyé", ar: "تم إرسال البريد" },
  "forgot.sentMsg": { fr: "Si un compte existe avec cet email, vous recevrez un lien pour réinitialiser votre mot de passe.", ar: "إذا كان هناك حساب بهذا البريد، ستتلقى رابطاً لإعادة تعيين كلمة المرور." },

  // Reset password
  "reset.title": { fr: "Nouveau mot de passe", ar: "كلمة مرور جديدة" },
  "reset.subtitle": { fr: "Choisissez un nouveau mot de passe pour votre compte", ar: "اختر كلمة مرور جديدة لحسابك" },
  "reset.newPassword": { fr: "Nouveau mot de passe", ar: "كلمة المرور الجديدة" },
  "reset.update": { fr: "Mettre à jour", ar: "تحديث" },
  "reset.updating": { fr: "Mise à jour...", ar: "جاري التحديث..." },
  "reset.loading": { fr: "Chargement...", ar: "جاري التحميل..." },

  // New Professional Options & Features Translations
  "space.nav.journal": { fr: "Journal d'humeur", ar: "دفتر يومياتي" },
  "space.nav.coping": { fr: "Outils de coping", ar: "تمارين التأقلم" },
  "space.journal.title": { fr: "Journal thérapeutique & Humeur", ar: "مذكرات علاجية وتتبع المزاج" },
  "space.journal.placeholder": { fr: "Comment s'est passée votre journée ? Écrivez ce que vous ressentez...", ar: "كيف كان يومك؟ اكتب ما تشعر به..." },
  "space.journal.save": { fr: "Enregistrer dans mon journal", ar: "حفظ في مذكراتي" },
  "space.journal.mood.happy": { fr: "Heureux", ar: "سعيد" },
  "space.journal.mood.calm": { fr: "Calme", ar: "هادئ" },
  "space.journal.mood.neutral": { fr: "Neutre", ar: "محايد" },
  "space.journal.mood.sad": { fr: "Triste", ar: "حزين" },
  "space.journal.mood.anxious": { fr: "Anxieux", ar: "قلق" },
  "space.journal.mood.angry": { fr: "En colère", ar: "غاضب" },
  "space.journal.history": { fr: "Historique du journal", ar: "سجل اليوميات" },
  "space.journal.noEntries": { fr: "Aucune note pour le moment. Écrivez votre première entrée !", ar: "لا توجد ملاحظات حالياً. اكتب تدوينتك الأولى!" },
  "space.journal.insights": { fr: "Statistiques d'humeur", ar: "إحصائيات المزاج" },
  "space.journal.insightsDesc": { fr: "Humeur fréquente :", ar: "المزاج المتكرر:" },
  "space.coping.title": { fr: "Exercices de relaxation & ancrage", ar: "تمارين الاسترخاء والتركيز" },
  "space.coping.breathing": { fr: "Respiration guidée (Carrée)", ar: "تنفس موجه (تنفس مربع)" },
  "space.coping.breathingDesc": { fr: "Un outil pour calmer le système nerveux lors d'une crise d'anxiété.", ar: "أداة لتهدئة الجهاز العصبي أثناء نوبة القلق." },
  "space.coping.breath.inhale": { fr: "Inspirez...", ar: "شهيق..." },
  "space.coping.breath.hold": { fr: "Bloquez...", ar: "احبس النفس..." },
  "space.coping.breath.exhale": { fr: "Expirez...", ar: "زفير..." },
  "space.coping.breath.start": { fr: "Commencer la respiration", ar: "بدء التنفس" },
  "space.coping.breath.stop": { fr: "Arrêter", ar: "إيقاف" },
  "space.coping.grounding": { fr: "Technique d'ancrage 5-4-3-2-1", ar: "تقنية التركيز 5-4-3-2-1" },
  "space.coping.groundingDesc": { fr: "Revenez au moment présent en stimulant vos 5 sens.", ar: "عد إلى اللحظة الحالية عن طريق تحفيز حواسك الخمس." },
  "space.crisis.title": { fr: "Besoin d'aide immédiate ?", ar: "هل تحتاج إلى مساعدة فورية؟" },
  "space.crisis.desc": { fr: "Si vous traversez une crise grave, contactez ces services d'urgence gratuits en Algérie.", ar: "إذا كنت تمر بأزمة حادة، اتصل بخدمات الطوارئ المجانية هذه في الجزائر." },
  "space.goals.title": { fr: "Mes objectifs thérapeutiques", ar: "أهدافي العلاجية" },
  "space.goals.add": { fr: "Ajouter un objectif", ar: "إضافة هدف" },
  "space.goals.placeholder": { fr: "Ex: Pratiquer la respiration...", ar: "مثال: ممارسة التنفس..." },
  "space.goals.notepad": { fr: "Préparation des séances", ar: "التحضير للجلسات" },
  "space.goals.notepadPlaceholder": { fr: "Notez ici les questions ou sujets à aborder...", ar: "اكتب هنا الأسئلة أو المواضيع التي تود مناقشتها..." },
  "psy.settings.clinic.title": { fr: "Configuration du cabinet", ar: "إعدادات العيادة" },
  "psy.settings.vacation.title": { fr: "Mode Vacances", ar: "وضع الإجازة" },
  "psy.settings.vacation.desc": { fr: "Bloque temporairement les nouvelles réservations.", ar: "يمنع الحجوزات الجديدة مؤقتاً." },
  "psy.settings.autoconfirm.title": { fr: "Confirmation automatique", ar: "تأكيد تلقائي" },
  "psy.settings.autoconfirm.desc": { fr: "Accepte automatiquement les séances réservées par les patients.", ar: "يقبل تلقائياً الجلسات التي يحجزها المرضى." },
  "psy.settings.accepting.title": { fr: "Accepter de nouveaux patients", ar: "قبول مرضى جدد" },
  "psy.settings.accepting.desc": { fr: "Affiche votre profil dans l'annuaire de recherche.", ar: "يظهر ملفك الشخصي في دليل البحث." },
  "psy.settings.vacationBanner": { fr: "Vous êtes actuellement en mode vacances. Les nouvelles réservations sont désactivées.", ar: "أنت حالياً في وضع الإجازة. تم إيقاف الحجوزات الجديدة." },
  "psy.settings.hours.title": { fr: "Heures de travail & Pause", ar: "ساعات العمل والراحة" },
  "psy.settings.hours.start": { fr: "Heure de début", ar: "وقت البدء" },
  "psy.settings.hours.end": { fr: "Heure de fin", ar: "وقت الانتهاء" },
  "psy.settings.hours.buffer": { fr: "Pause entre séances (min)", ar: "وقت الراحة بين الجلسات (دقائق)" },
  "psy.settings.hours.days": { fr: "Jours de travail", ar: "أيام العمل" },
  "psy.patients.drawer.title": { fr: "Détails du Patient", ar: "تفاصيل المريض" },
  "psy.patients.notes.title": { fr: "Notes cliniques confidentielles", ar: "ملاحظات علاجية سرية" },
  "psy.patients.notes.placeholder": { fr: "Rédigez vos observations confidentielles (historique médical, diagnostics, progrès thérapeutique)... Ces notes ne sont visibles que par vous.", ar: "اكتب ملاحظاتك السرية (التاريخ الطبي، التشخيص، التقدم العلاجي)... هذه الملاحظات لا يراها أحد سواك." },
  "psy.patients.notes.save": { fr: "Sauvegarder les notes cliniques", ar: "حفظ الملاحظات العلاجية" },
  "psy.patients.notes.success": { fr: "Notes cliniques enregistrées avec succès !", ar: "تم حفظ الملاحظات العلاجية بنجاح!" },
  "psy.earnings.receipt.title": { fr: "Reçu de Paiement", ar: "وصل استلام الدفع" },
  "psy.earnings.receipt.invoiceNum": { fr: "Facture N°", ar: "فاتورة رقم" },
  "psy.earnings.receipt.date": { fr: "Date d'émission", ar: "تاريخ الإصدار" },
  "psy.earnings.receipt.patient": { fr: "Facturé à (Patient)", ar: "مفوتر إلى (المريض)" },
  "psy.earnings.receipt.therapist": { fr: "Praticien", ar: "المعالج" },
  "psy.earnings.receipt.desc": { fr: "Désignation de la prestation", ar: "تسمية الخدمة" },
  "psy.earnings.receipt.sessionVal": { fr: "Séance de psychothérapie individuelle (60 min)", ar: "جلسة علاج نفسي فردية (60 دقيقة)" },
  "psy.earnings.receipt.generate": { fr: "Générer un reçu", ar: "وصل" },
  "psy.earnings.receipt.print": { fr: "Imprimer le reçu", ar: "طباعة الوصل" },
  "psy.earnings.receipt.statusPaid": { fr: "Statut : PAYÉ", ar: "الحالة: مدفوع" },
  "psy.earnings.receipt.signature": { fr: "Cachet et Signature", ar: "الختم والتوقيع" },

  // Social Media Features
  "space.nav.explore": { fr: "Découvrir", ar: "اكتشف" },
  "space.nav.forum": { fr: "Forum d'entraide", ar: "منتدى الدعم" },
  "psy.dashboard.nav.content": { fr: "Création de contenu", ar: "إنشاء المحتوى" },
  "space.explore.title": { fr: "Découvrir & Se ressourcer", ar: "اكتشف واستعد طاقتك" },
  "space.explore.stories": { fr: "Réflexions du jour", ar: "تأملات اليوم" },
  "space.explore.gratitude": { fr: "Mur des Gratitudes", ar: "جدار الامتنان" },
  "space.explore.gratitudeDesc": { fr: "Partagez anonymement une chose positive de votre journée.", ar: "شارك بشكل مجهول شيئاً إيجابياً من يومك." },
  "space.explore.addGratitude": { fr: "Exprimer ma gratitude", ar: "التعبير عن امتناني" },
  "space.explore.gratitudePlaceholder": { fr: "Aujourd'hui, je suis reconnaissant pour...", ar: "اليوم، أنا ممتن لـ..." },
  "space.explore.postGratitude": { fr: "Épingler au mur", ar: "تثبيت على الجدار" },
  "space.forum.title": { fr: "Forum de soutien anonyme", ar: "منتدى الدعم المجهول" },
  "space.forum.desc": { fr: "Partagez vos défis et soutenez les autres membres en toute sécurité et anonymat.", ar: "شارك تحدياتك وادعم الأعضاء الآخرين بأمان وسرية تامة." },
  "space.forum.newTopic": { fr: "Nouveau sujet", ar: "موضوع جديد" },
  "space.forum.postTitle": { fr: "Titre du sujet", ar: "عنوان الموضوع" },
  "space.forum.postContent": { fr: "Votre message...", ar: "رسالتك..." },
  "space.forum.createPost": { fr: "Publier anonymement", ar: "نشر بشكل مجهول" },
  "space.forum.comments": { fr: "Réponses", ar: "الردود" },
  "space.forum.reply": { fr: "Répondre", ar: "رد" },
  "space.forum.replyPlaceholder": { fr: "Écrire une réponse d'encouragement...", ar: "اكتب رداً تشجيعياً..." },
  "space.forum.verifiedPsy": { fr: "Psychologue Vérifié", ar: "أخصائي نفسي معتمد" },
  "space.streaks.checkin": { fr: "Série bien-être", ar: "سلسلة العافية" },
  "space.streaks.days": { fr: "jours consécutifs", ar: "أيام متtالية" },
  "space.streaks.badges": { fr: "Mes badges et exploits", ar: "شاراتي وإنجازاتي" },
  "space.explore.liveRooms": { fr: "Groupes d'écoute en direct", ar: "مجموعات الإصغاء المباشرة" },
  "space.explore.joinRoom": { fr: "Rejoindre le cercle", ar: "انضمام للحلقة" },
  "space.explore.leaveRoom": { fr: "Quitter le salon", ar: "مغادرة الصالون" },
  "space.explore.speakers": { fr: "Intervenants", ar: "المتحدثون" },
  "space.explore.listeners": { fr: "Auditeurs", ar: "المستمعون" },
  "space.explore.requestSpeak": { fr: "Demander la parole", ar: "طلب التحدث" },
  "psy.content.publishStory": { fr: "Publier une Réflexion", ar: "نشر تأمل" },
  "psy.content.storyText": { fr: "Votre réflexion ou citation bien-être", ar: "تأملك أو اقتباسك للعافية" },
  "psy.content.storyBg": { fr: "Preset de fond coloré", ar: "خلفية ملونة جاهزة" },
  "psy.content.liveAudio": { fr: "Salon Audio en Direct", ar: "صالون صوتي مباشر" },
  "psy.content.startAudio": { fr: "Lancer le salon en direct", ar: "بدء صالون مباشر" },
  "psy.content.activeSpeakers": { fr: "Intervenants actifs", ar: "المتحدثون النشطون" },
  "psy.content.topicTitle": { fr: "Sujet du salon", ar: "موضوع الصالون" },
  "psy.content.topicPlaceholder": { fr: "Ex: Gérer l'anxiété au travail...", ar: "مثال: التعامل مع القلق في العمل..." },

  // MonEspace sidebar & dashboard
  "space.sidebar.findPsy": { fr: "Trouver un psychologue", ar: "البحث عن أخصائي" },
  "space.sidebar.patient": { fr: "Patient", ar: "مريض" },
  "space.sidebar.logout": { fr: "Déconnexion", ar: "تسجيل الخروج" },
  "space.dashboard.greeting": { fr: "Bonjour", ar: "مرحباً" },
  "space.dashboard.welcomeMsg": { fr: "Bienvenue dans votre espace personnel Majal.", ar: "مرحباً بكم في مساحتكم الشخصية في مجال." },
  "space.dashboard.bookNew": { fr: "Réserver une nouvelle séance", ar: "حجز جلسة جديدة" },
  "space.dashboard.totalSessions": { fr: "Séances totales", ar: "إجمالي الجلسات" },
  "space.dashboard.therapyHours": { fr: "Heures de thérapie", ar: "ساعات العلاج" },
  "space.dashboard.upcomingCount": { fr: "Séances à venir", ar: "الجلسات القادمة" },
  "space.dashboard.upcomingTitle": { fr: "Prochaines séances", ar: "الجلسات القادمة" },
  "space.dashboard.viewAll": { fr: "Voir tout", ar: "عرض الكل" },
  "space.dashboard.noUpcoming": { fr: "Aucune séance programmée à venir.", ar: "لا توجد جلسات مجدولة قادمة." },
  "space.dashboard.noUpcomingHelp": { fr: "Besoin d'aide ? Prenez un rendez-vous avec l'un de nos praticiens certifiés.", ar: "هل تحتاج مساعدة؟ احجز موعداً مع أحد أطبائنا المعتمدين." },
  "space.dashboard.findPsyBtn": { fr: "Trouver un psychologue", ar: "البحث عن أخصائي" },
  "space.dashboard.crisisTitle": { fr: "Besoin d'aide immédiate ?", ar: "هل تحتاج مساعدة فورية؟" },
  "space.dashboard.emergencyNums": { fr: "Numéro Vert National (Gendarmerie)", ar: "الرقم الأخضر الوطني (الدرك الوطني)" },
  "space.dashboard.civilProtection": { fr: "Protection Civile", ar: "الحماية المدنية" },
  "space.dashboard.police": { fr: "Police Secours", ar: "شرطة الإغاثة" },
  "space.dashboard.security": { fr: "Sécurité", ar: "الأمان" },
  "space.dashboard.newPassword": { fr: "Nouveau mot de passe", ar: "كلمة مرور جديدة" },
  "space.dashboard.update": { fr: "Mise à jour...", ar: "جاري التحديث..." },
  "space.dashboard.changePassword": { fr: "Changer le mot de passe", ar: "تغيير كلمة المرور" },

  // EspacePsy common
  "psy.common.patient": { fr: "Patient", ar: "مريض" },
  "psy.common.close": { fr: "Fermer", ar: "إغلاق" },
  "psy.common.approved": { fr: "APPROUVÉ", ar: "معتمد" },
  "psy.common.total": { fr: "Total", ar: "الإجمالي" },
  "psy.common.status": { fr: "Statut :", ar: "الحالة:" },
  "psy.common.verified": { fr: "Compte Vérifié ✓", ar: "حساب موثق ✓" },
  "psy.common.verifying": { fr: "Vérification en cours...", ar: "جارٍ التحقق..." },
  "psy.common.actionRequired": { fr: "Action requise", ar: "إجراءات مطلوبة" },
  "psy.common.lastVisit": { fr: "Dernière visite", ar: "آخر زيارة" },
  "psy.common.totalSessions": { fr: "Séances totales", ar: "إجمالي الجلسات" },
  "psy.common.secureNotes": { fr: "🔒 Ces notes cliniques sont stockées de manière sécurisée et confidentielle.", ar: "🔒 هذه الملاحظات العلاجية مخزنة بشكل آمن وسري." },
  "psy.common.lastAppointment": { fr: "Dernier rendez-vous", ar: "آخر موعد" },
  "psy.common.sessions": { fr: "Séances", ar: "الجلسات" },
  "psy.common.upload": { fr: "Upload...", ar: "رفع..." },
  "psy.common.change": { fr: "Changer", ar: "تغيير" },
  "psy.common.formatHint": { fr: "Formats acceptés : JPG, PNG, WEBP (max 5 Mo)", ar: "الصيغ المقبولة: JPG, PNG, WEBP (حد أقصى 5 ميغا)" },
  "psy.common.onlineConsult": { fr: "Espace de consultation en ligne", ar: "فضاء الاستشارة عبر الإنترنت" },

  // Reservation toasts
  "res.error.loadProfile": { fr: "Impossible de charger le profil du psychologue.", ar: "تعذر تحميل ملف الأخصائي النفسي." },
  "res.error.notAvailable": { fr: "Ce psychologue n'est pas encore disponible.", ar: "هذا الأخصائي النفسي غير متاح حالياً." },
  "res.error.invalidId": { fr: "ID de psychologue invalide.", ar: "معرف الأخصائي النفسي غير صالح." },
  "res.error.loginRequired": { fr: "Vous devez être connecté pour réserver.", ar: "يجب تسجيل الدخول للحجز." },
  "res.error.slotTaken": { fr: "Ce créneau est déjà réservé. Veuillez en choisir un autre.", ar: "هذا الموعد محجوز بالفعل. يرجى اختيار موعد آخر." },
  "res.error.general": { fr: "Une erreur est survenue. Veuillez réessayer.", ar: "حدث خطأ. يرجى المحاولة مرة أخرى." },
  "res.error.paymentRedirect": { fr: "Erreur de redirection vers le paiement.", ar: "خطأ في التحويل إلى صفحة الدفع." },
  "res.viewBookings": { fr: "Voir mes réservations", ar: "عرض حجوزاتي" },

  // Chat
  "chat.sendFailed": { fr: "Échec de l'envoi du message", ar: "فشل إرسال الرسالة" },
  "chat.fileSent": { fr: "Fichier envoyé", ar: "تم إرسال الملف" },
  "chat.fileFailed": { fr: "Échec de l'envoi du fichier", ar: "فشل إرسال الملف" },
  "chat.micPermission": { fr: "Veuillez autoriser l'accès au microphone.", ar: "يرجى السماح بالوصول إلى الميكروفون." },
  "chat.voiceFailed": { fr: "Message vocal non envoyé", ar: "لم يتم إرسال الرسالة الصوتية" },
  "chat.noMessages": { fr: "Aucun message. Envoyez un petit coucou !", ar: "لا توجد رسائل. أرسل تحية!" },
  "chat.attachFile": { fr: "Joindre un fichier", ar: "إرفاق ملف" },
  "chat.recording": { fr: "Enregistrement en cours...", ar: "جارٍ التسجيل..." },
  "chat.placeholder": { fr: "Écrivez un message...", ar: "اكتب رسالة..." },
  "chat.holdToRecord": { fr: "Maintenir pour enregistrer", ar: "اضغط مع الاستمرار للتسجيل" },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: (key) => key,
  dir: "ltr",
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("majal-lang") as Lang) || "fr";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("majal-lang", l);
  };

  const t = (key: string): string => {
    return translations[key]?.[lang] || key;
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang, dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
